### ISSUE TITLE
Some modifications that allow Travelling Salesman Solutions to tracked locations

### ISSUE THREAD

**Issue by CeruleanSky** [MrCheeze/botw-waypoint-map#1]
To map.py I added the following, and for less confusion, swapped Z and Y in the code.

```
import numpy, pytspsa
locations = []
[...](https://github.com/MrCheeze/botw-waypoint-map/blob/gh-pages/map.py#L43)
x,y,z = float(translate.attrib['X'].rstrip('f')), float(translate.attrib['Z'].rstrip('f')), float(translate.attrib['Y'].rstrip('f'))
f2.write('{"internal_name":"%s", "display_name":"%s", "x":%g, "y":%g, "z":%g},\n' % (saveflag, name, x, y, z))
locations.append((x,y,z))
img_x = int(x/2 + 3000)
img_y = int(z/2 + 2500)
...
tspsolver = pytspsa.Tsp_sa()
locations_np = numpy.asarray(locations, dtype=numpy.float32)
tspsolver.set_num_nodes(len(locations))
tspsolver.add_by_coordinates(locations_np)
tspsolver.set_t_v_factor(200.0 / len(locations))
tspsolver.sa_auto_parameter(24)
tspsolution = tspsolver.getBestSolution()
tsproute = tspsolution.getRoute().split('-')
tsproute.pop()

past_point = None
for p in tsproute :
    x,y,z = locations_np[int(p)].tolist()
    if past_point != None:
        map_draw.line((past_point, (x/2 + 3000, y/2 + 2500)), fill='red', width=3)
    past_point = (x/2 + 3000, y/2 + 2500)
...
botw_map.save('BotW-Map-Labeled' + str(tspsolution.getlength()) + '.png',optimize=True)
```

Within a few seconds a nice path around the map was created, then I renamed the file and had it loaded in index.html  

I did  change index.html to load BotW-Map-Labeled.png and changed style of .waypoint:hover { to have opacity: 1; and .waypoint to have opacity: 0 for better display.

The solution is produced extremely quickly, even quicker if you keep it 2d. 

The demo code for pytspsa has the following:

```
    if len(c) <= 100:
        solver.set_t_v_factor(min(t_v_factor, 200.0 / len(c)))
    else:
        solver.set_t_v_factor(min(t_v_factor, 60.0 / len(c)))
```

And auto parameter can be lowered to 8 and such, if the waypoints start to get into the thousands, but since most points are only a few dozen or hundred, the parameters should be fine as it stands. 

Example produced map for some shrines I needed to visit with mostly convex solutions:

![a](https://user-images.githubusercontent.com/2829875/28661246-0b631e52-7284-11e7-8bd5-71998c75b11b.png)

**Comment by MrCheeze** [comment]
See reply [here.](https://github.com/MrCheeze/botw-object-map/issues/6)
